// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	model "ScheduleJobs/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: job
func (_m *Repository) Create(job model.Job) (model.Job, error) {
	ret := _m.Called(job)

	var r0 model.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Job) (model.Job, error)); ok {
		return rf(job)
	}
	if rf, ok := ret.Get(0).(func(model.Job) model.Job); ok {
		r0 = rf(job)
	} else {
		r0 = ret.Get(0).(model.Job)
	}

	if rf, ok := ret.Get(1).(func(model.Job) error); ok {
		r1 = rf(job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: jobID
func (_m *Repository) Find(jobID int) (model.Job, error) {
	ret := _m.Called(jobID)

	var r0 model.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (model.Job, error)); ok {
		return rf(jobID)
	}
	if rf, ok := ret.Get(0).(func(int) model.Job); ok {
		r0 = rf(jobID)
	} else {
		r0 = ret.Get(0).(model.Job)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
